weights: yolov5m6.pt
cfg: ''
data: /home/zkhan1/YOLOv5_FOSOCO_Dataset/yolov5/data/data.yaml
hyp:
  lr0: 0.00258
  lrf: 0.17
  momentum: 0.779
  weight_decay: 0.00058
  warmup_epochs: 1.33
  warmup_momentum: 0.86
  warmup_bias_lr: 0.0711
  box: 0.0539
  cls: 0.299
  cls_pw: 0.825
  obj: 0.632
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 3.44
  anchors: 3.2
  fl_gamma: 0.0
  hsv_h: 0.0188
  hsv_s: 0.704
  hsv_v: 0.36
  degrees: 0.0
  translate: 0.0902
  scale: 0.491
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 200
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '1'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: train_background_augment_360
name: feature_extraction
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 12
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: train_background_augment_360/feature_extraction
